### ISSUE TITLE
cache usage

### ISSUE THREAD

**Issue by nkv123** [burghardt/clamfs#2]
<cache entries="16384" expire="10800000" /> 
How big is one cache entry?
I do not want cache to have more then 256MB of my ram memory.

**Comment by burghardt** [comment]
Cache is ExpireLRUCache<ino_t, CachedResult>. For x86_64 Linux ino_t is 8 bytes and CachedResult is 16 bytes. My rough estimation is more than 10 millions entries in 256MB. This do not include size of ExpireLRUCache internals. According to "find / -type f | wc -l" I have only 1,5 milion files on my laptop.
