### ISSUE TITLE
clamfs-1.3.0 release tarball

### ISSUE THREAD

**Issue by jsmolic** [burghardt/clamfs#78]
Hello, 
I noticed that version 1.3.0 was tagged in the commits, but I can't find a release tarball. Is it possible to release the tarball so I can push the update downstream to Gentoo?

Thanks

**Comment by burghardt** [comment]
Hi! 1.3.0 wasn't tagged/released yet. If you take a look at https://github.com/burghardt/clamfs/tags 1.2.0 is the last one. 1.3.0 is WiP with no ETA,
